#! /bin/bash

IFS='$\n'
LOG_FILE="{{LOG}}"

if [[ -n $1 ]]
then
    filepath="$1"
    if [[ -z $2 ]]
    then
        while read -r line
        do
            timestamp=$(date "+%F %R:%S.%N" | cut -b1-19)
            echo "I|$timestamp|$filepath|$line" >> "$LOG_FILE"
        done
    else
        if [[ $# -eq 2 && $2 == '-e' ]]
        then
            while read -r line
            do
                timestamp=$(date "+%F %R:%S.%N" | cut -b1-19)
                echo "E|$timestamp|$filepath|$line" >> "$LOG_FILE"
            done
        else
            echo "Wrong parameter" >&2
        fi
    fi
else
    echo "Wrong parameter" >&2
fi
