#! /bin/bash

IFS='$\n'
logdir="$BOTTLE_DIR/logs"
path="$1"

if [[ -n $path ]]
then
    name=$(basename "$path" .exe)
    start_time=$(date '+%F %R:%S')
    logfile="$logdir/$name.log"
    unset newfile
    if [[ ! -e $logfile ]]
    then
        newfile=true
    else
        checkpath=$(head -n1 "$logfile")
        i=0
        while [[ $path != $checkpath ]] && [[ -z $newfile ]]
        do
            logfile="$logdir/$name.$i.log"
            if [[ ! -e $logfile ]]
            then
                newfile=true
            else
                checkpath=$(head -n1 "$logfile")
                let i++
            fi
        done
    fi

    if $newfile
    then
        echo $path > "$logfile"
    fi
    echo >> "$logfile"
    echo $start_time >> "$logfile"
    while read -r line
    do
        timestamp=$(date "+%F %R:%S.%N" | cut -b1-19)
        echo "$timestamp|$line" >> "$logfile"
    done
fi
