#! /usr/bin/bash

if [[ -n $1 ]]
then
    export BOTTLE_NAME="$1"
    export WINERY_ACTIVE="$BOTTLE_NAME"
    export BOTTLE_PATH="$HOME/.winery/bottles/$BOTTLE_NAME"
    export BOTTLE_BITNESS=$(grep bitness= < $BOTTLE_PATH/bottle | sed -e "s/bitness=//")
    export BOTTLE_WINEPREFIX=$(grep wineprefix= < $BOTTLE_PATH/bottle | sed -e "s/wineprefix=//")
    export PS1_OLD="$PS1"
    export PS1="($BOTTLE_NAME) $PS1_OLD"
    if command -v winetricks &> /dev/null
    then
        export BOTTLE_TRICK=1
        source "$HOME/Code/bottler/_winetricks"
    fi
fi

function config {
    (WINEPREFIX=$BOTTLE_WINEPREFIX WINEARCH=$BOTTLE_BITNESS winecfg &> /dev/null &)
}

function nuke {
    (WINEPREFIX=$BOTTLE_WINEPREFIX WINEARCH=$BOTTLE_BITNESS wineboot -k &> /dev/null &)
}

function cmd {
    (WINEPREFIX=$BOTTLE_WINEPREFIX WINEARCH=$BOTTLE_BITNESS wineconsole &> /dev/null &)
}

function file {
    (WINEPREFIX=$BOTTLE_WINEPREFIX WINEARCH=$BOTTLE_BITNESS winefile &> /dev/null &)
}

function lsexe {
    find "$BOTTLE_PATH/wineprefix" -type f -iname "*.exe"
}

function exe {
    if [[ -n $1 ]]
    then
        (WINEPREFIX=$BOTTLE_WINEPREFIX WINEARCH=$BOTTLE_BITNESS wine $1 &> /dev/null &)
    fi
}

function addshortcut {
    if [[ $# -ge 2 ]]
    then
        SHORTCUT_NAME="$1"
        SHORTCUT_PATH="$2"
        unset SHORTCUT_ARGS
        unset SHORTCUT_ENV
        shift 2
        while [[ -n $1 ]]
        do
            case $1 in
                '-a')
                    SHORTCUT_ARGS="$2"
                    shift 2
                ;;
                '-e')
                    SHORTCUT_ENV="$2"
                    shift 2
                ;;
                *)
                    shift
                ;;
            esac
        done
        touch "$BOTTLE_PATH/shortcuts/$SHORTCUT_NAME"
        echo "name=$SHORTCUT_NAME" >> "$BOTTLE_PATH/shortcuts/$SHORTCUT_NAME"
        echo "path=$SHORTCUT_PATH" >> "$BOTTLE_PATH/shortcuts/$SHORTCUT_NAME"
        if [[ -n $SHORTCUT_ARGS ]]
        then
            echo "args=$SHORTCUT_ARGS" >> "$BOTTLE_PATH/shortcuts/$SHORTCUT_NAME"
        fi
        if [[ -n $SHORTCUT_ENV ]]
        then
            echo "env=$SHORTCUT_ENV" >> "$BOTTLE_PATH/shortcuts/$SHORTCUT_NAME"
        fi
    fi
}

function rmshortcut {
    if [[ -f "$BOTTLE_PATH/shortcuts/$1" ]]
    then
        rm -f "$BOTTLE_PATH/shortcuts/$1"
    fi
}

function mvshortcut {
    if [[ -n $1 && -n $2 ]]
    then
        if [[ -f "$BOTTLE_PATH/shortcuts/$1" ]]
        then
            mv "$BOTTLE_PATH/shortcuts/$1" "$BOTTLE_PATH/shortcuts/$2" &&
            sed -i -e "s/name=.*/name=$2/" "$BOTTLE_PATH/shortcuts/$2"
        fi
    fi
}

function lsrun {
    for SHORTCUT in $BOTTLE_PATH/shortcuts/$1/*
    do
        if [[ -f $SHORTCUT ]]
        then
            NAME=$(grep name= < $SHORTCUT | sed -e "s/name=//")
            if [[ -n $NAME ]]
            then
                echo "$NAME"
            fi
        fi
    done
}

function run {
    if [[ -f $BOTTLE_PATH/shortcuts/$1 ]]
    then
        EXE_PATH=$(grep path= < $BOTTLE_PATH/shortcuts/$1 | sed -e "s/path=//")
        SHORTCUT_ENV=$(grep env= < $BOTTLE_PATH/shortcuts/$1 | sed -e "s/env=//")
        SHORTCUT_ARGS=$(grep args= < $BOTTLE_PATH/shortcuts/$1 | sed -e "s/args=//")
        if [[ -f $EXE_PATH ]]
        then
            (env $SHORTCUT_ENV WINEPREFIX=$BOTTLE_WINEPREFIX WINEARCH=$BOTTLE_BITNESS wine $EXE_PATH $SHORTCUT_ARGS &> /dev/null &)
        fi
    fi
}

function open {
    xdg-open "$BOTTLE_WINEPREFIX/drive_c"
}

function cork {
    nuke
    export PS1="$PS1_OLD"
    unset BOTTLE_NAME
    unset WINERY_ACTIVE
    unset BOTTLE_PATH
    unset BOTTLE_BITNESS
    unset BOTTLE_WINEPREFIX
    unset PS1_OLD
    unset -f config
    unset -f cmd
    unset -f exe
    unset -f run
    unset -f lsexe
    unset -f open
    unset -f lsrun
    unset -f mvshortcut
    unset -f rmshortcut
    unset -f addshortcut
    unset -f file
    unset -f nuke
    unset -f cork
    if [[ $BOTTLE_TRICK == 1 ]]
    then
        unset $BOTTLE_TRICK
        unset -f lsdll
        unset -f lsfont
        unset -f lsset
        unset -f lsinst
        unset -f trick
    fi
}
