#! /usr/bin/bash

function lsdll {
    WINEPREFIX=$BOTTLE_WINEPREFIX WINEARCH=$BOTTLE_BITNESS winetricks dlls list
}

function lsfont {
    WINEPREFIX=$BOTTLE_WINEPREFIX WINEARCH=$BOTTLE_BITNESS winetricks fonts list
}

function lsset {
    WINEPREFIX=$BOTTLE_WINEPREFIX WINEARCH=$BOTTLE_BITNESS winetricks settings list
}

function lsinst {
    WINEPREFIX=$BOTTLE_WINEPREFIX WINEARCH=$BOTTLE_BITNESS winetricks list-installed
}

function trick {
    WINEPREFIX=$BOTTLE_WINEPREFIX WINEARCH=$BOTTLE_BITNESS winetricks $@
}
