#! /bin/bash

if [[ $1 == "-i" ]]
then
    env WINEPREFIX={{WINEPREFIX}} WINEARCH={{BITNESS}} wineconsole --backend=curses 2> >("$BOTTLE_DIR/logger" $(command -v wineconsole) "-e")
else
    (env WINEPREFIX={{WINEPREFIX}} WINEARCH={{BITNESS}} wineconsole --backend=user > >("$BOTTLE_DIR/logger" $(command -v wineconsole)) 2> >("$BOTTLE_DIR/logger" $(command -v wineconsole) "-e") &)
fi
