#! /bin/bash

if [[ -n $1 ]]
then
    if [[ -f $1 ]]
    then
        EXE_DIR=${1%/*}
        (cd "$EXE_DIR" ; env WINEPREFIX="$BOTTLE_WINEPREFIX" WINEARCH="$BOTTLE_BITNESS" wine "$1" &> >("$BOTTLE_DIR/logger" "$1") &)
    else
        echo "No such file"
    fi
else
    echo "No file specified"
fi
