#! /bin/bash

if [[ -f "{{WINEPREFIX}}/drive_c/windows/explorer.exe" ]]
then
    (env WINEPREFIX={{WINEPREFIX}} WINEARCH={{BITNESS}} wine "{{WINEPREFIX}}/drive_c/windows/explorer.exe" > >("$BOTTLE_DIR/logger" "{{WINEPREFIX}}/drive_c/windows/explorer.exe") 2> >("$BOTTLE_DIR/logger" "{{WINEPREFIX}}/drive_c/windows/explorer.exe" "-e") &)
else
    echo "explorer.exe not found"
fi
