#! /bin/bash

if [[ -f "{{WINEPREFIX}}/drive_c/windows/explorer.exe" ]]
then
    (env WINEPREFIX={{WINEPREFIX}} WINEARCH={{BITNESS}} wine "{{WINEPREFIX}}/drive_c/windows/explorer.exe" &> /dev/null &)
else
    echo "explorer.exe not found"
fi
