#! /bin/bash

if [[ -f "$BOTTLE_WINEPREFIX/drive_c/windows/system32/iexplore.exe" ]]
then
    (env WINEPREFIX="$BOTTLE_WINEPREFIX" WINEARCH="$BOTTLE_BITNESS" wine "$BOTTLE_WINEPREFIX/drive_c/windows/system32/iexplore.exe" > >("$BOTTLE_DIR/logger" "$BOTTLE_WINEPREFIX/drive_c/windows/system32/iexplore.exe") 2> >("$BOTTLE_DIR/logger" "$BOTTLE_WINEPREFIX/drive_c/windows/system32/iexplore.exe" "-e") &)
else
    echo "iexplore.exe not found"
fi
