#! /bin/bash

if [[ -f "$BOTTLE_WINEPREFIX/drive_c/windows/notepad.exe" ]]
then
    (env WINEPREFIX="$BOTTLE_WINEPREFIX" WINEARCH="$BOTTLE_BITNESS" wine "$BOTTLE_WINEPREFIX/drive_c/windows/notepad.exe" > >("$BOTTLE_DIR/logger" "$BOTTLE_WINEPREFIX/drive_c/windows/notepad.exe") 2> >("$BOTTLE_DIR/logger" "$BOTTLE_WINEPREFIX/drive_c/windows/notepad.exe" "-e") &)
else
    echo "notepad.exe not found"
fi
