#! /bin/bash

if [[ -f {{WINEPREFIX}}/drive_c/windows/regedit.exe ]]
then
    (env WINEPREFIX={{WINEPREFIX}} WINEARCH={{BITNESS}} wine "{{WINEPREFIX}}/drive_c/windows/regedit.exe" &> /dev/null &)
else
    echo "regedit.exe not found"
fi
