#! /bin/bash

if [[ -f "$BOTTLE_WINEPREFIX/drive_c/windows/system32/taskmgr.exe" ]]
then
    (env WINEPREFIX="$BOTTLE_WINEPREFIX" WINEARCH="$BOTTLE_BITNESS" wine "$BOTTLE_WINEPREFIX/drive_c/windows/system32/taskmgr.exe" > >("$BOTTLE_DIR/logger" "$BOTTLE_WINEPREFIX/drive_c/windows/system32/taskmgr.exe") 2> >("$BOTTLE_DIR/logger" "$BOTTLE_WINEPREFIX/drive_c/windows/system32/taskmgr.exe" "-e") &)
else
    echo "taskmgr.exe not found"
fi
