#! /bin/bash

if [[ -f "{{WINEPREFIX}}/drive_c/windows/system32/taskmgr.exe" ]]
then
    (env WINEPREFIX={{WINEPREFIX}} WINEARCH={{BITNESS}} wine "{{WINEPREFIX}}/drive_c/windows/system32/taskmgr.exe" &> /dev/null &)
else
    echo "taskmgr.exe not found"
fi
